### ISSUE TITLE
Feature: Support custom or no S3 prefixes on keys for self-hosted caching

### ISSUE THREAD

**Issue by Makeshift** [runs-on/cache#21]
When using this action with a self-hosted bucket, runs-on/cache will save to a bucket key along the lines of `s3://bucket/cache/${user}/${repo}/...`.

Would it be possible to add an env var to customise the format of this key, or alternatively an env var to disable the prefix used by the action and to simply use the key given in the `key` action property, with no prefix?

For example, my cache key has slashes in it which, if placed in the root of the bucket, would put the cache where I want it to be:

```yaml
      - name: Init Maven repo cache
        env:
          RUNS_ON_S3_BUCKET_CACHE: ${{ steps.resolve.outputs.bucket }}
          RUNS_ON_AWS_REGION: ${{ steps.resolve.outputs.region }}
        uses: runs-on/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-repo-cache/${{ runner.os }}-${{ github.repository }}/${{ hashFiles('**/pom.xml') }}
```

But with the prefix added by the action, it actually ends up in: `s3://${bucket}/cache/${user}/${repo}/${hash}/maven-repo-cache/${os}-${user}/${repo}/${hash}` 

This makes it a bit more awkward to have a generalised lifecycle rule to manage caches, since the runs-on cache prefix isn't where my other caches are configured to be.

Cheers!
