### ISSUE TITLE
Decommissioned cache services causing brownouts

### ISSUE THREAD

**Issue by shanesavoie** [runs-on/cache#32]
https://github.blog/changelog/2025-03-20-notification-of-upcoming-breaking-changes-in-github-actions/#decommissioned-cache-service-brownouts

Hi, just bringing this to your attention. We were using runs-on/cache and were hit with a brownout. There may be some updates that need to happen with the runs-on/cache repo.

**Comment by caquino** [comment]
@shanesavoie I'm not sure if you faced the same issue as me, but I had some repositories returning the error `Warning: An internal error has occurred in cache backend. Please check https://www.githubstatus.com/ for any ongoing issue in actions.`

This happened because `actions/runner` receives the information from GitHub API and sets the `ACTIONS_CACHE_URL` environment variable. And if GitHub API does not return this information, the variable will not be set. You can see this [here](https://github.com/actions/runner/blob/d9e714496d037f8f8130ac080afc0d8bc07b3f00/src/Runner.Worker/Handlers/NodeScriptActionHandler.cs#L57-L60)

Now if you check the `runs-on/cache` code (to be fair, this came from the original `actions/cache` repository), there is a check [here](https://github.com/runs-on/cache/blob/7b6f0057823efdadca0b2a0d1173d7f8d3d90199/src/utils/actionUtils.ts#L64-L66). 

This check occurs even when using S3 as a cache. Therefore, if GitHub does not set `ACTIONS_CACHE_URL` because the API does not return it, this action will break.

The workaround while there is no code fix is to just set `ACTIONS_CACHE_URL` to any value, this will allow the check to pass and not cause any side effects as this environment variable is not used for S3 caching.

So you would have something like this on your workflows:
```
  - uses: aws-actions/configure-aws-credentials@v4
    ...
  - uses: runs-on/cache@v4
    with:
      ...
    env:
      RUNS_ON_S3_BUCKET_CACHE: name-of-your-bucket
      ACTIONS_CACHE_URL: cache-brownout-workaround
```

I hope this information helps anyone else affected by this issue.
