### ISSUE TITLE
`~/.cache/Cypress` not restored when using relative paths (runs-on/cache vs actions/cache)

### ISSUE THREAD

**Issue by kopach** [runs-on/cache#36]
When using the runs-on/cache action to restore the cache for ~/.cache/Cypress (as recommended by Cypress), the binary is **not restored properly**. This issue does not occur when using the standard actions/cache action.

**Steps to Reproduce:**

1. Use the following cache restore step:

```yml
- name: Restore pnpm cache
  id: pnpm_cache
  uses: actions/cache/restore@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
  with:
    path: |
      ~/.cache/Cypress
      node_modules
  key: ${{ runner.os }}-dependencies-${{ hashFiles('**/pnpm-lock.yaml') }}
```

2. Cache is saved as expected.
  
3. On restore, the binary in ~/.cache/Cypress is missing.
  
4. Using an **absolute path** (/root/.cache/Cypress) instead of ~/.cache/Cypress **works as expected**.

**Expected Behavior:**

- runs-on/cache should restore the binary in ~/.cache/Cypress using the **relative home path** ~/.cache/Cypress, consistent with behavior in actions/cache.

**Refs:**

- Cypress’s documentation recommends using ~/.cache/Cypress for caching: https://docs.cypress.io/app/continuous-integration/overview#Caching
- actions/cache works fine with the relative path, they even recommend it, see examples: https://github.com/actions/cache/blob/main/examples.md
