### ISSUE TITLE
v4.0 save always not working

### ISSUE THREAD

**Issue by ruffsl** [runs-on/cache#5]
Same as the `github/cache` it would seem:
- https://github.com/actions/cache/issues/1315

![image](https://github.com/runs-on/cache/assets/2293573/b128ac0a-b99f-493c-ab9f-97bcf9adef4c)

```
Run runs-on/cache@v4
  with:
    save-always: true
    path: <path>
    key: <key>
    enableCrossOsArchive: false
    fail-on-cache-miss: false
    lookup-only: false

/usr/bin/docker exec  702dea252a610926dd2a414e706d60182f9fbb67b16a8adcda50b8cab36b4795 sh -c "cat /etc/*release | grep ^ID"
The cache action detected a local S3 bucket cache. Using it.
Cache not found for input keys: <keys>
```

![image](https://github.com/runs-on/cache/assets/2293573/abfff7f0-6358-4b11-8837-809e7962ae3c)

Related Fix:
- https://github.com/actions/cache/pull/1325

**Comment by ruffsl** [comment]
@crohr , perhaps a fix something like the above could be used? I was successfully using this workaround prior:

```yaml
      - name: Cache ccache
        id: cache_ccache
        uses: actions/cache@3a22487daddcfa2ebf7238869de052504cc6dc4b
        with:
          save-always: true
          path: |
            ${{ inputs.overlay_ws }}/.ccache
          key: "🗃️-ccache-v1\
            -${{ github.ref }}\
            -${{ github.run_id }}\
            -${{ github.run_number }}\
            -${{ github.run_attempt }}"
          restore-keys: |
            🗃️-ccache-v1-${{ github.ref }}
            🗃️-ccache-v1-refs/heads/${{ github.head_ref }}
            🗃️-ccache-v1-refs/heads/${{ github.base_ref }}
```
